# 開発用
# version: "3"
# services:
#   app:
#     image: nft-market-dev
#     build: .
#     ports:
#       - 3000:3000
#     volumes:
#       - ./pages:/app/pages
#       - ./public:/app/public
#       - ./styles:/app/styles

# 本番用
version: "3"
services:
  app:
    image: nft-market-production
    build:
      dockerfile: Dockerfile.production
    ports:
      - 3000:3000
